apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox:musl
    name: busybox
    resources: {}
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /etc/foo
      name: cache-volume
  - image: busybox:musl
    name: busybox2
    resources: {}
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /etc/foo
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 50Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
