apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    command: ["/bin/sh", "-c", "echo hello; sleep 3600"]
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: temp-volume
  initContainers:
  - name: init-busybox
    image: busybox
    command: ["bin/sh", "-c", 'echo "Test" > /work-dir/index.html']
    volumeMounts:
    - mountPath: /work-dir
      name: temp-volume
  volumes:
  - name: temp-volume
    emptyDir:
      sizeLimit: 50Mi
