apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        cpu: 100
        memory: 256Mi
      limits:
        cpu: 200
        memory: 512Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
