apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: foo
      mountPath: "/etc/lala"
      readOnly: true
  volumes:
  - name: foo
    configMap:
      name: cmvolume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
