apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    env:
    - name: envVar1
      valueFrom:
        configMapKeyRef:
          name: anotherone
          key: var6
    - name: envVar2
      valueFrom:
        configMapKeyRef:
          name: anotherone
          key: var7
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
