apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: consumer
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    env:
    - name: ENVVAR
      valueFrom:
        secretKeyRef:
          name: ext-service-secret
          key: API_KEY
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
