apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    metadata: {}
    spec:
      containers:
      - image: busybox
        name: myjob
        resources: {}
      restartPolicy: Never
  parallelism: 5
  completions: 5
status: {}
