apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: tier
    operator: "Equal"
    value: frontend
    effect: "NoSchedule"
  nodeName: minikube-m02
status: {}
